"""add_version_start_end_date

Revision ID: 5a96b484e2b1
Revises: 1de04bd4a29d
Create Date: 2026-07-31 15:17:52.659865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a96b484e2b1'
down_revision: Union[str, None] = '1de04bd4a29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('versions', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'end_date')
    op.drop_column('versions', 'start_date')
    # ### end Alembic commands ###
